import { Activity, Info } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ErrorState } from "@/components/ui/error-state";
import { getCalibration } from "@/lib/api";
import { formatPercent } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function CalibrationPage() {
  try {
    const report = await getCalibration();
    const max = Math.max(1, ...report.buckets.map((b) => b.count));
    return <><PageHeader eyebrow="Outcome feedback" title="Calibration" description="When DecisionOS expresses confidence, compare it with observed success. Only decisions with recorded outcomes count." />
      <div className="mb-4 grid gap-3 sm:grid-cols-3"><MetricCard label="Calibrated samples" value={report.sample_count.toLocaleString()} hint="Decisions with outcomes" /><MetricCard label="Brier score" value={report.brier_score === null ? "n/a" : report.brier_score.toFixed(4)} hint="Lower is better · 0 is perfect" /><MetricCard label="Expected calibration error" value={report.expected_calibration_error === null ? "n/a" : report.expected_calibration_error.toFixed(4)} hint="Weighted confidence–accuracy gap" /></div>
      <div className="grid gap-4 xl:grid-cols-[1.25fr_0.75fr]">
        <Card><CardHeader><CardTitle>Reliability curve</CardTitle><p className="text-xs text-muted-foreground">Perfect calibration falls on the diagonal. Points reflect recorded outcomes only.</p></CardHeader><CardContent>{report.buckets.length ? <div className="grid gap-6 md:grid-cols-[minmax(0,1fr)_180px]"><div className="relative aspect-square max-h-[420px] w-full overflow-hidden rounded border border-border bg-[#080d17]"><div className="absolute inset-0" style={{ backgroundImage: "linear-gradient(to right, rgba(71,85,105,.18) 1px, transparent 1px), linear-gradient(to bottom, rgba(71,85,105,.18) 1px, transparent 1px)", backgroundSize: "20% 20%" }} /><div className="absolute inset-0"><div className="absolute bottom-[10%] left-[10%] h-[1px] w-[80%] rotate-[-45deg] bg-muted-foreground/50" />{report.buckets.map((bucket) => { const x = 10 + bucket.avg_confidence * 80; const y = 90 - bucket.accuracy * 80; const size = 8 + (bucket.count / max) * 12; return <div key={`${bucket.lower}-${bucket.upper}`} title={`${formatPercent(bucket.avg_confidence)} confidence, ${formatPercent(bucket.accuracy)} accuracy, n=${bucket.count}`} className="absolute rounded-full border-2 border-primary bg-primary/50" style={{ left: `${x}%`, top: `${y}%`, width: size, height: size, transform: "translate(-50%, -50%)" }} />; })}</div><div className="absolute bottom-2 left-1/2 -translate-x-1/2 text-[9px] text-muted-foreground">Mean confidence →</div><div className="absolute left-2 top-1/2 -translate-y-1/2 -rotate-90 text-[9px] text-muted-foreground">Accuracy →</div></div><div><p className="mb-3 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Bucket detail</p><div className="space-y-2">{report.buckets.map((b) => <div key={`${b.lower}-${b.upper}`} className="rounded-md border border-border bg-background/60 p-2.5"><div className="mb-1 flex justify-between text-[10px]"><span className="font-mono">{b.lower.toFixed(1)}–{b.upper.toFixed(1)}</span><span className="text-muted-foreground">n={b.count}</span></div><div className="flex justify-between text-[10px] text-muted-foreground"><span>Accuracy {formatPercent(b.accuracy)}</span><span>Conf. {formatPercent(b.avg_confidence)}</span></div></div>)}</div></div></div> : <div className="flex h-64 flex-col items-center justify-center text-center"><Activity className="mb-3 h-5 w-5 text-muted-foreground" /><p className="text-sm font-medium">No observed outcomes yet</p><p className="mt-1 max-w-md text-xs text-muted-foreground">Record outcomes against decisions to build a calibration curve. Predictions alone cannot measure calibration.</p></div>}</CardContent></Card>
        <Card className="h-fit"><CardHeader><CardTitle className="flex items-center gap-2"><Info className="h-4 w-4 text-primary" />How to read this</CardTitle></CardHeader><CardContent className="space-y-4 text-xs leading-relaxed text-muted-foreground"><p><strong className="text-foreground">Brier score</strong> is the mean squared difference between confidence and observed correctness. Smaller is better.</p><p><strong className="text-foreground">ECE</strong> averages the gap between confidence and accuracy across reliability buckets, weighted by sample count.</p><p>Each sample is a decision with a recorded outcome. The outcome&apos;s <code className="rounded bg-secondary px-1 py-0.5">success</code> field is ground truth; decisions without outcomes are excluded.</p><div className="rounded-md border border-border bg-background p-3"><p className="mb-1 font-medium text-foreground">No synthetic statistics</p><p>Empty or insufficient data is shown as unavailable rather than replaced with demo numbers.</p></div></CardContent></Card>
      </div>
    </>;
  } catch (error) { return <><PageHeader eyebrow="Outcome feedback" title="Calibration" /><ErrorState message={error instanceof Error ? error.message : "API unavailable"} /></>; }
}

function MetricCard({ label, value, hint }: { label: string; value: string; hint: string }) {
  return <Card className="p-5"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 font-mono-nums text-2xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{hint}</p></Card>;
}
