"""initial schema

Revision ID: b05babe204f0
Revises: 
Create Date: 2026-09-24 19:17:41.975201
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b05babe204f0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_decision_schemas_name_version')
    )
    op.create_index('ix_decision_schemas_name', 'decision_schemas', ['name'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_type', sa.String(length=128), nullable=False),
    sa.Column('schema_name', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('model_action', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk', sa.Float(), nullable=True),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('policy_name', sa.String(length=128), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('policy_overridden', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_action', 'decisions', ['action'], unique=False)
    op.create_index('ix_decisions_created_at', 'decisions', ['created_at'], unique=False)
    op.create_index('ix_decisions_decision_type', 'decisions', ['decision_type'], unique=False)
    op.create_index('ix_decisions_idempotency_key', 'decisions', ['idempotency_key'], unique=False)
    op.create_index('ix_decisions_provider', 'decisions', ['provider'], unique=False)
    op.create_index('ix_decisions_schema', 'decisions', ['schema_name', 'schema_version'], unique=False)
    op.create_index('ix_decisions_state', 'decisions', ['state'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_policy_versions_name_version')
    )
    op.create_index('ix_policy_versions_name', 'policy_versions', ['name'], unique=False)
    op.create_table('decision_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_events_decision_id', 'decision_events', ['decision_id'], unique=False)
    op.create_index('ix_decision_events_occurred_at', 'decision_events', ['occurred_at'], unique=False)
    op.create_table('decision_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('actual_outcome', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_outcomes_decision_id', 'decision_outcomes', ['decision_id'], unique=False)
    op.create_index('ix_decision_outcomes_recorded_at', 'decision_outcomes', ['recorded_at'], unique=False)
    op.create_table('decision_probabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'action', name='uq_decision_probabilities_decision_action')
    )
    op.create_index('ix_decision_probabilities_decision_id', 'decision_probabilities', ['decision_id'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('policy_name', sa.String(length=128), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('precedence', sa.String(length=32), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('final_action', sa.String(length=64), nullable=False),
    sa.Column('triggered_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_evaluations_decision_id', 'policy_evaluations', ['decision_id'], unique=False)
    op.create_index('ix_policy_evaluations_policy', 'policy_evaluations', ['policy_name', 'policy_version'], unique=False)
    op.create_table('provider_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_kind', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_requests_created_at', 'provider_requests', ['created_at'], unique=False)
    op.create_index('ix_provider_requests_decision_id', 'provider_requests', ['decision_id'], unique=False)
    op.create_index('ix_provider_requests_provider', 'provider_requests', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_requests_provider', table_name='provider_requests')
    op.drop_index('ix_provider_requests_decision_id', table_name='provider_requests')
    op.drop_index('ix_provider_requests_created_at', table_name='provider_requests')
    op.drop_table('provider_requests')
    op.drop_index('ix_policy_evaluations_policy', table_name='policy_evaluations')
    op.drop_index('ix_policy_evaluations_decision_id', table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index('ix_decision_probabilities_decision_id', table_name='decision_probabilities')
    op.drop_table('decision_probabilities')
    op.drop_index('ix_decision_outcomes_recorded_at', table_name='decision_outcomes')
    op.drop_index('ix_decision_outcomes_decision_id', table_name='decision_outcomes')
    op.drop_table('decision_outcomes')
    op.drop_index('ix_decision_events_occurred_at', table_name='decision_events')
    op.drop_index('ix_decision_events_decision_id', table_name='decision_events')
    op.drop_table('decision_events')
    op.drop_index('ix_policy_versions_name', table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index('ix_decisions_state', table_name='decisions')
    op.drop_index('ix_decisions_schema', table_name='decisions')
    op.drop_index('ix_decisions_provider', table_name='decisions')
    op.drop_index('ix_decisions_idempotency_key', table_name='decisions')
    op.drop_index('ix_decisions_decision_type', table_name='decisions')
    op.drop_index('ix_decisions_created_at', table_name='decisions')
    op.drop_index('ix_decisions_action', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_decision_schemas_name', table_name='decision_schemas')
    op.drop_table('decision_schemas')
    # ### end Alembic commands ###
